/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.26.4-7-g20e17559e (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.26.4-7-g20e17559e"
#endif
#define SDL_REVISION_NUMBER 0
