#This make file is used with Watcom C/C++ 32 Compiler v10.5
!ifdef rrra
# rides again
prod = /5r /otexan /d2 /bt=DOS -DRRRA
!else
# redneck rampage
prod = /5r /otexan /bt=DOS
!endif

!ifdef rrra
ra.exe : game1.obj game2.obj game3.obj game4.obj game5.obj game6.obj game7.obj game8.obj game9.obj &
			actors1.obj actors2.obj actors3.obj actors4.obj actors5.obj actors6.obj &
			gamedef1.obj gamedef2.obj global.obj menus1.obj menus2.obj menus3.obj &
			player1.obj player2.obj player3.obj player4.obj player5.obj &
			premap.obj sector1.obj sector2.obj sector3.obj sounds.obj rts.obj &
			config.obj animlib.obj &
			lava.obj noise.obj warpfx.obj dpmi.obj _debug.obj rbaudio.obj
		wlink $(all) @makefil2.lnk
!else
rr.exe : game1.obj game2.obj game3.obj game4.obj game5.obj game6.obj game7.obj game8.obj game9.obj &
			actors1.obj actors2.obj actors3.obj actors4.obj actors5.obj actors6.obj &
			gamedef1.obj gamedef2.obj global.obj menus1.obj menus2.obj menus3.obj &
			player1.obj player2.obj player3.obj player4.obj player5.obj &
			premap.obj sector1.obj sector2.obj sector3.obj sounds.obj rts.obj &
			config.obj animlib.obj &
			lava.obj noise.obj warpfx.obj dpmi.obj _debug.obj rbaudio.obj
		wlink $(all) @makefile.lnk
!endif

compileoptions = $(prod) $(debug) -imact
globaldependencies = makefile. duke3d.h global.c

game1.obj : game1.c $(globaldependencies)
	wcc386 game1 $(compileoptions)
game2.obj : game2.c $(globaldependencies)
	wcc386 game2 $(compileoptions)
game3.obj : game3.c $(globaldependencies)
	wcc386 game3 $(compileoptions)
game4.obj : game4.c $(globaldependencies)
	wcc386 game4 $(compileoptions)
game5.obj : game5.c $(globaldependencies)
	wcc386 game5 $(compileoptions)
game6.obj : game6.c $(globaldependencies)
	wcc386 game6 $(compileoptions)
game7.obj : game7.c $(globaldependencies)
	wcc386 game7 $(compileoptions)
game8.obj : game8.c $(globaldependencies)
	wcc386 game8 $(compileoptions)
game9.obj : game9.c $(globaldependencies)
	wcc386 game9 $(compileoptions)
actors1.obj : actors1.c $(globaldependencies)
	wcc386 actors1 $(compileoptions)
actors2.obj : actors2.c $(globaldependencies)
	wcc386 actors2 $(compileoptions)
actors3.obj : actors3.c $(globaldependencies)
	wcc386 actors3 $(compileoptions)
actors4.obj : actors4.c $(globaldependencies)
	wcc386 actors4 $(compileoptions)
actors5.obj : actors5.c $(globaldependencies)
	wcc386 actors5 $(compileoptions)
actors6.obj : actors6.c $(globaldependencies)
	wcc386 actors6 $(compileoptions)
gamedef1.obj : gamedef1.c $(globaldependencies)
	wcc386 gamedef1 $(compileoptions)
gamedef2.obj : gamedef2.c $(globaldependencies)
	wcc386 gamedef2 $(compileoptions)
global.obj : global.c $(globaldependencies)
	wcc386 global $(compileoptions)
menus1.obj : menus1.c $(globaldependencies)
	wcc386 menus1 $(compileoptions)
menus2.obj : menus2.c $(globaldependencies)
	wcc386 menus2 $(compileoptions)
menus3.obj : menus3.c $(globaldependencies)
	wcc386 menus3 $(compileoptions)
player1.obj : player1.c $(globaldependencies)
	wcc386 player1 $(compileoptions)
player2.obj : player2.c $(globaldependencies)
	wcc386 player2 $(compileoptions)
player3.obj : player3.c $(globaldependencies)
	wcc386 player3 $(compileoptions)
player4.obj : player4.c $(globaldependencies)
	wcc386 player4 $(compileoptions)
player5.obj : player5.c $(globaldependencies)
	wcc386 player5 $(compileoptions)
premap.obj : premap.c $(globaldependencies)
	wcc386 premap $(compileoptions)
sector1.obj : sector1.c $(globaldependencies)
	wcc386 sector1 $(compileoptions)
sector2.obj : sector2.c $(globaldependencies)
	wcc386 sector2 $(compileoptions)
sector3.obj : sector3.c $(globaldependencies)
	wcc386 sector3 $(compileoptions)
sounds.obj : sounds.c $(globaldependencies)
!ifdef rrra
	wcc386 sounds /zu $(compileoptions)
!else
	wcc386 sounds $(compileoptions)
!endif
rts.obj : rts.c $(globaldependencies)
	wcc386 rts $(compileoptions)
config.obj : config.c $(globaldependencies)
	wcc386 config $(compileoptions)
animlib.obj : animlib.c $(globaldependencies)
	wcc386 animlib $(compileoptions)
lava.obj : lava.c $(globaldependencies)
	wcc386 lava $(compileoptions)
noise.obj : noise.c $(globaldependencies)
	wcc386 noise $(compileoptions)
warpfx.obj : warpfx.c $(globaldependencies)
	wcc386 warpfx $(compileoptions)
dpmi.obj : dpmi.c $(globaldependencies)
	wcc386 dpmi $(compileoptions)
_debug.obj : _debug.c $(globaldependencies)
	wcc386 _debug $(compileoptions)
rbaudio.obj : rbaudio.c $(globaldependencies)
	wcc386 rbaudio $(compileoptions)

